---
abstract: 'DBI-compliant interface for Neo4j server'
author:
  - 'Mark A. Jensen'
build_requires:
  DBI: '1.632'
  Module::Build: '0'
  REST::Neo4p: '0.3030'
  Test::Exception: '0'
  Test::More: '0'
  experimental: '0'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4224, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DBD-Neo4p
provides:
  DBD::Neo4p:
    file: lib/DBD/Neo4p.pm
    version: '0.2001'
requires:
  DBI: '1.632'
  JSON: '0'
  REST::Neo4p: '0.3030'
resources:
  bugtracker: http://github.com/majensen/dbd-neo4p.git/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/majensen/dbd-neo4p.git
version: '0.2001'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
